name: workflow

on: 
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    if: github.event.pull_request.merged == true
  deploy:
    name: deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY:
          REMOTE_HOST:
          REMOTE_USER:
          TAREGT: